services:
  - type: web
    name: monitor-mercado-argy
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      # MONITOR_PORT mapea a la misma variable que espera nuestro settings
      - key: MONITOR_PORT
        value: 8000
      - key: MONITOR_HOST
        value: 0.0.0.0
